f_dirmov (len) =>
    float up = ta.change(high)
    float dn = -ta.change(low)
    float truerange = ta.rma(ta.tr, len)
    float plus = fixnan(100 * ta.rma((up > dn) and (up > 0) ? up : 0, len) / truerange)
    float minus = fixnan(100 * ta.rma((dn > up) and (dn > 0) ? dn : 0, len) / truerange)

    [plus, minus]

f_adx (di_len, adx_len) =>
    [plus, minus] = f_dirmov(di_len)
    float sum = plus + minus
    float adx = 100 * ta.sma(math.abs(plus - minus) / (sum == 0 ? 1 : sum), adx_len)

    [adx, plus, minus]
